create table inventory (
    id bigint generated by default as identity primary key,
    store_id varchar(64) not null,
    product_id varchar(128) not null,
    quantity integer not null check (quantity >= 0),
    version bigint not null,
    updated_at timestamp with time zone not null
);

create unique index uk_inventory_store_product on inventory (store_id, product_id);
create index idx_inventory_store on inventory (store_id);
